image: openjdk:17
variables:
  JAVA_HOME: /lib/jvm/java-17-openjdk-amd64
stages:
  - Build
  - Check
build:
  stage: Build
  script:
    - chmod +x gradlew
    - ./gradlew clean assemble
check:
  stage: Check
  script:
    - chmod +x gradlew
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest