image: openjdk:17
variables:
  JAVA_HOME: /lib/jvm/java-17-openjdk-amd64
stages:
  - Build
  - Check
  - TestAPI
  - TestGUI

build:
  stage: Build
  script:
    - chmod +x gradlew
    - ./gradlew clean assemble
check:
  stage: Check
  script:
    - chmod +x gradlew
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest
TestAPI:
  allow_failure: true
  stage: TestAPI
  script:
    - pwd
    - chmod +x gradlew
    - ./gradlew clean executeFeatures -PcucumberOptions="@API" -PenvId="local" -PbaseURL="$baseURL" -PlogURL="$loginURL" -PadminURL="$adminURL" -PnPostURL="$newPostURL" -PnTagURL="$editTagURL" -PadminUser="$adminUsername" -PadminPass="$adminUserPassword" -PauthUser="$authorUsername" -PauthPass="$authorUserPassword" -PcontrUser="$contributorUsername" -PcontrPass="$contributorUserPassword" -PeditUser="$editorUsername" -PeditPass="$editorUserPassword" -PsubsUser="$subscriberUsername" -PsubsPass="$subscriberUserPassword"
  artifacts:
    when: always
    paths:
      - reports/

TestUI:
  allow_failure: true
  stage: TestGUI
  script:
      - pwd
      - chmod +x gradlew
      - ./gradlew clean executeFeatures -PcucumberOptions="@UI" -PenvId="local" -PbuildNumber="10" -Pbrowser="chrome" -PheadlessMode="true" -PbaseURL="$baseURL" -PlogURL="$loginURL" -PadminURL="$adminURL" -PnPostURL="$newPostURL" -PnTagURL="$editTagURL" -PadminUser="$adminUsername" -PadminPass="$adminUserPassword" -PauthUser="$authorUsername" -PauthPass="$authorUserPassword" -PcontrUser="$contributorUsername" -PcontrPass="$contributorUserPassword" -PeditUser="$editorUsername" -PeditPass="$editorUserPassword" -PsubsUser="$subscriberUsername" -PsubsPass="$subscriberUserPassword"