image: openjdk:17
variables:
  JAVA_HOME: /lib/jvm/java-17-openjdk-amd64
stages:
  - Build
  - Check
  - Test
build:
  stage: Build
  script:
    - chmod +x gradlew
    - ./gradlew clean assemble
check:
  stage: Check
  script:
    - chmod +x gradlew
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest
test:
  allow_failure: true
  stage: Test
  script:
    - pwd
    - chmod +x gradlew
    - ./gradlew clean executeFeatures -PcucumberOptions="@API" -PenvId="local" -PbaseURL="$baseURL" -PlogURL="$loginURL" -PadminURL="$adminURL" -PnPostURL="$newPostURL" -PnTagURL="$editTagURL" -PadminUser="$adminUsername" -PadminPass="$adminUserPassword" -PauthUser="$authorUsername" -PauthPass="$authorUserPassword" -PcontrUser="$contributorUsername" -PcontrPass="$contributorUserPassword" -PeditUser="$editorUsername" -PeditPass="$editorUserPassword" -PsubsUser="$subscriberUsername" -PsubsPass="$subscriberUserPassword"